// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: test1_pb.proto

package trpc_Test1Pb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// HttpService defines service.
type HttpService interface {
	// HelloLipei @alias=/lipei/hello
	HelloLipei(ctx context.Context, req *HelloLipeiReq) (*HelloLipeiReq, error)
}

func HttpService_HelloLipei_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloLipeiReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HttpService).HelloLipei(ctx, reqbody.(*HelloLipeiReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// HttpServer_ServiceDesc descriptor for server.RegisterService.
var HttpServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.Test1Pb.http",
	HandlerType: ((*HttpService)(nil)),
	Methods: []server.Method{
		{
			Name: "/lipei/hello",
			Func: HttpService_HelloLipei_Handler,
		},
		{
			Name: "/trpc.Test1Pb.http/HelloLipei",
			Func: HttpService_HelloLipei_Handler,
		},
	},
}

// RegisterHttpService registers service.
func RegisterHttpService(s server.Service, svr HttpService) {
	if err := s.Register(&HttpServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Http register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedHttp struct{}

// HelloLipei @alias=/lipei/hello
func (s *UnimplementedHttp) HelloLipei(ctx context.Context, req *HelloLipeiReq) (*HelloLipeiReq, error) {
	return nil, errors.New("rpc HelloLipei of service Http is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// HttpClientProxy defines service client proxy
type HttpClientProxy interface {
	// HelloLipei @alias=/lipei/hello
	HelloLipei(ctx context.Context, req *HelloLipeiReq, opts ...client.Option) (rsp *HelloLipeiReq, err error)
}

type HttpClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewHttpClientProxy = func(opts ...client.Option) HttpClientProxy {
	return &HttpClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *HttpClientProxyImpl) HelloLipei(ctx context.Context, req *HelloLipeiReq, opts ...client.Option) (*HelloLipeiReq, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/lipei/hello")
	msg.WithCalleeServiceName(HttpServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("http")
	msg.WithCalleeMethod("HelloLipei")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloLipeiReq{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
