// Code generated by MockGen. DO NOT EDIT.
// Source: test1_pb.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=test_1_pb_mock.go -package=pb --source=test1_pb.trpc.go -self_package=trpc.test1_pb/pb
//

// Package pb is a generated GoMock package.
package pb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockHttpService is a mock of HttpService interface.
type MockHttpService struct {
	ctrl     *gomock.Controller
	recorder *MockHttpServiceMockRecorder
}

// MockHttpServiceMockRecorder is the mock recorder for MockHttpService.
type MockHttpServiceMockRecorder struct {
	mock *MockHttpService
}

// NewMockHttpService creates a new mock instance.
func NewMockHttpService(ctrl *gomock.Controller) *MockHttpService {
	mock := &MockHttpService{ctrl: ctrl}
	mock.recorder = &MockHttpServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpService) EXPECT() *MockHttpServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockHttpService) ISGOMOCK() struct{} {
	return struct{}{}
}

// HelloLipei mocks base method.
func (m *MockHttpService) HelloLipei(ctx context.Context, req *HelloLipeiReq) (*HelloLipeiReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HelloLipei", ctx, req)
	ret0, _ := ret[0].(*HelloLipeiReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HelloLipei indicates an expected call of HelloLipei.
func (mr *MockHttpServiceMockRecorder) HelloLipei(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HelloLipei", reflect.TypeOf((*MockHttpService)(nil).HelloLipei), ctx, req)
}

// MockHttpClientProxy is a mock of HttpClientProxy interface.
type MockHttpClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientProxyMockRecorder
}

// MockHttpClientProxyMockRecorder is the mock recorder for MockHttpClientProxy.
type MockHttpClientProxyMockRecorder struct {
	mock *MockHttpClientProxy
}

// NewMockHttpClientProxy creates a new mock instance.
func NewMockHttpClientProxy(ctrl *gomock.Controller) *MockHttpClientProxy {
	mock := &MockHttpClientProxy{ctrl: ctrl}
	mock.recorder = &MockHttpClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpClientProxy) EXPECT() *MockHttpClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockHttpClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// HelloLipei mocks base method.
func (m *MockHttpClientProxy) HelloLipei(ctx context.Context, req *HelloLipeiReq, opts ...client.Option) (*HelloLipeiReq, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HelloLipei", varargs...)
	ret0, _ := ret[0].(*HelloLipeiReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HelloLipei indicates an expected call of HelloLipei.
func (mr *MockHttpClientProxyMockRecorder) HelloLipei(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HelloLipei", reflect.TypeOf((*MockHttpClientProxy)(nil).HelloLipei), varargs...)
}
